name: haptic_composer_example
description: "Example app demonstrating the haptic_composer package."
publish_to: 'none'

version: 0.0.2+1

environment:
  sdk: ^3.10.4
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  haptic_composer:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
